# Spring common-application-properties
spring:
  datasource:
    url: jdbc:mysql://zemoga-test-db.crhpedy9xxto.us-east-1.rds.amazonaws.com:3306/zemoga_test_db
    username: zemoga_test_db
    password: Zem0ga.101
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 
  #propiedad spring.thymeleaf.cache se debe colocar en false para deshabilitar la cache y poder aplicar cambien en caliente con spring loaded
  thymeleaf:
      cache: false
 
#Application properties
zemoga:
 twitter:
  dev:
    apikey: KRy7l0v8wex3w8Sy5zThai3Ea
    apisecretkey: X2eBm0Y21kYEuR74W3Frqc2JVIizOj8Q1EVGatDsEVVEJo0ucu
    accesstoken: 1220032047516921859-otvXjhExyUTZ5GLxssc9h5ORqtPZja
    accesstokensecret: tmJKqM4ORfQW6CH7wIVV8uKNpmSEmeFAP8lYwGb19uYjj
    endpoint: https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=Zemoga&count=5